openapi: 3.1.0
info:
  title: Product Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://bww8ctkjf3.execute-api.ca-central-1.amazonaws.com/prod
    description: AWS API Gateway
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      examples: "1"
                    name:
                      type: string
                      examples: "Product 1"
                    price:
                      type: number
                      examples: 100
  /products/{productId}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: string
            examples: "1"
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    examples: "1"
                  name:
                    type: string
                    examples: "Product 1"
                  price:
                    type: number
                    examples: 100
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    examples: "Product not found"